# Generated by Django 3.0.7 on 2020-10-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_lib', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id_num',
            new_name='number',
        ),
    ]
