# Generated by Django 3.0.7 on 2020-10-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_lib', '0002_auto_20201010_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, help_text='Dostępność książki'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.CharField(help_text='Year/number: YYYY/num', max_length=9, unique=True),
        ),
    ]
