# Generated by Django 3.0.7 on 2020-10-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_lib', '0005_auto_20201023_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='book',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='historicalbook',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='historicalbook',
            name='due_back',
        ),
    ]
